### PR TITLE
Use ST_Intersects function to exclude

### PR DESCRIPTION
**Pull request by BCCghspace**
Hi Andy! I am not sure if this needs editing. Both methods work (and apparently the one you use is much more simple), but since the question mentions the ST_Intersects function, I think maybe the one right here is what you expect of us to do. But anyway, I think it's fine if you leave it as the "!=" format. I just do a pull request in case you didn't make it this way on purpose.

### CODE REVIEW

**Comment by andy-esch** [comment]
@BCCghspace, nice one :) Yeah, both are valid. And actually, if we didn't have a `name` attribute for Meyerson Hall and instead only had the geometry to uniquely define it, your method would be a great one. 

I'd remove the `geography` casting here because the intersects in the 2d plane of geometries is good and faster:

```sql
ST_Intersects(the_geom, ST_SetSRID(ST_MakePoint(-75.19265679, 39.9522405), 4326))
```

**Comment by andy-esch** [comment]
Actually, if you want to add this as another example below the one I put that does the string filter, that'd be nice :)

**Comment by BCCghspace** [comment]
I see. That makes sense. 
And sure, I can do that! I just edited it :)

**Comment by andy-esch** [comment]
Thank you! Could you do one more update and put the full query instead of just the WHERE clause? Many thanks :)

**Comment by BCCghspace** [comment]
Glad to help :）

**Pull request merged**
